### ISSUE TITLE
How Can I disable the AX200 bluetooth device

### ISSUE THREAD

**Issue by echokk11** [barrrrt/AMD-3900x_MEG-MSI-Unify-X570_AMD-X5700XT#1]
First thx a lot, I use the EFI, and pefect running Hackintosh in my PC.

I try the intel ax200 driver, but it is not work for me.
So I bought a Broadcom card.

I have turn off the board wireless in bios

I remove the intel bluetooth kext in Kexts folder and remove in config.plist too.

![Xnip2021-04-19_18-20-42](https://user-images.githubusercontent.com/8499152/115221237-080b4c80-a13c-11eb-839f-5c3a0fe3d63d.jpg)

 bluetooth is still not working , and the toggle button is disabled. can not click it.

**Comment by barrrrt** [comment]
XHCI - PRT4 should be the USB port for the BT/WLAN device. You could try to disable that.
I had issued with the Intel WIFI/BT card, too. I didn't even test the driver that has been developed the last months.

When you say you bought a Broadcom card - does that mean it is a PCIE card? You didn't replace the Broadcom card with the intel card, right? 
After my replacement in the motherboard I don't see the AX200 card (of course no-one should see that card afterwards).

**Comment by echokk11** [comment]
Yes I bought a PCIE card. 
You mean I should take the device AX200 off the x570 board?

**Comment by barrrrt** [comment]
If you have a PCI-E card, then you don't have to take it off. Just deactivate the USB port with the SSDT-XHC....aml.
When the appropriate is deactivated you shouldn't see your AX200 any longer.

**Comment by echokk11** [comment]
I will try, and thanks a lot again for taking your time, bro.
Also apologize my poor English :(

**Comment by barrrrt** [comment]
Don't worry :D im also not a native speaker :P 
Ill close the case. If you need further assistance, just post here again (maybe with attached EFI then).

**Comment by echokk11** [comment]
I tried a google search and found that the aml file is a binary file and I need a decompiled editor, but I couldn't find a suitable one after searching for a long time. I have to decompile the aml file into an asl file, modify it, and then compile it into an aml file to use it. Can you give me some advice?

Another method is to remove the ax200 on the motherboard, but it has a steel frame protection, it seems that it is not an easy method.

And I found that my case is the same as yours, is it Fractal Design Define R5?

This is my configuration
3900x
MEG x570 unify
asus 5700xt
...

**Comment by barrrrt** [comment]
use Maciasl.

And I have the same fractal tower is guess.... I just had a different GPU (but also a 5700xt).

**Comment by echokk11** [comment]
In the end, I succeeded
I modify the `SSDT-XHC-customized.aml` file and delete the PRT4 node, it is not work 4 me.
I reset nvram, even mv `SSDT-XHC-customized.aml` to `SSDT-XHC-customized1.aml` and change the config.list, it is not useful too.

Finally, I open the  `USBPorts.kext` file in Kexts folder. edit the Info.plist file in Contents, remove the PRT4 node.
I didn’t expect to succeed, I even wanted to give up.
but.....
it is happend....
the ax200 is gone.. the BT works well....

**Comment by echokk11** [comment]
I am a java programmer. I have a 2019 15-inch macbook pro, but only 16G of memory, so I decided to assemble a hackintosh to improve the development experience. 😂. now is 16G*4.😊

**Comment by echokk11** [comment]
Monterey is coming. Have you upgraded your computer? I tried myself and it did not work  😂

**Comment by barrrrt** [comment]
Hi.. i have sold my Hackintosh. Im just using an Mac mini M1 since more than a half year.

Sometimes im missing my hackintosh and want to try new stuff out... 
but on the other hand I saved a lot of time just using the MacMini :P
